"""
AI Signal routes — list, filter, and retrieve trading signals generated by the AI Engine.
"""

from typing import List

from fastapi import APIRouter, Depends, Path, Query
from sqlalchemy.ext.asyncio import AsyncSession

from app.core.database import get_db
from app.db.schemas import SignalOut, PaginatedSignalsOut

router = APIRouter()


@router.get("", response_model=PaginatedSignalsOut)
async def list_signals(
    page: int = Query(default=1, ge=1),
    limit: int = Query(default=50, ge=1, le=500),
    status_filter: str = Query(default="all", alias="status"),
    db: AsyncSession = Depends(get_db),
) -> PaginatedSignalsOut:
    """Return paginated signals with optional status filter."""
    raise NotImplementedError("signals.list — implement in signal service")


@router.get("/active", response_model=List[SignalOut])
async def get_active(db: AsyncSession = Depends(get_db)) -> List[SignalOut]:
    """
    Return all currently pending signals.
    These are the signals the bot is watching for entry conditions.
    """
    raise NotImplementedError("signals.active — implement in signal service")


@router.get("/{id}", response_model=SignalOut)
async def get_signal(
    id: str = Path(...),
    db: AsyncSession = Depends(get_db),
) -> SignalOut:
    """Return a single signal by its UUID."""
    raise NotImplementedError("signals.get — implement in signal service")
