kind = "api"
previewPath = "/api"
title = "API Server"
version = "1.0.0"
id = "3B4_FFSkEVBkAeYMFRJ2e"

[[services]]
localPort = 8000
name = "API Server"
paths = ["/api"]

[services.development]
run = "cd backend && pip install -r requirements.txt -q && python main.py"

[services.production]

[services.production.run]
args = ["python", "backend/main.py"]

[services.production.health.startup]
path = "/api/healthz"
